### ISSUE TITLE
Dashboard Table and Charts

### ISSUE THREAD

**Issue by shu3hamiitkgp** [BigDataIA-Spring2023-Team-09/Assignment_3#14]
In the dashboard, there is a table showing all the users and their activity. This can be removed and made specific to the user logged in. 
Also, the x-axis in the last chart should ideally represent the date, but currently, its showing some sort of index which can be corrected

**Comment by Hmittal15** [comment]
Highlighted issues had been fixed and locally deployed. Due to deadline crunch we could not dockerize and host them on cloud VM instance. Same had been discussed with TA. Thanks for bringing it up.
<img width="1112" alt="image" src="https://user-images.githubusercontent.com/108916132/225720072-81b2d9d6-025e-4cd1-9388-004f06b5a2b6.png">

We will proceed to deploy this on cloud as well.
